---
networks:
  neo4j-network:
    driver: bridge

services:

  pipeline:
    container_name: s2s_pipeline
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    command: 
      - python3 
      - s2s_pipeline.py 
      - --recv_host 
      - 0.0.0.0 
      - --send_host 
      - 0.0.0.0 
      - --lm_model_name 
      - microsoft/Phi-3-mini-4k-instruct 
      - --init_chat_role 
      - system
      - --tts
      - xttsv2
      - --tts_compile_mode 
      - default
      - --stt_compile_mode 
      - reduce-overhead
      - --stt_model_name
      - openai/whisper-large-v3
      - --language
      - ru
      - --log_level
      - info
    expose:
      - 12345/tcp
      - 12346/tcp
    ports:
      - 12345:12345/tcp
      - 12346:12346/tcp
    volumes:
      - ./cache/:/root/.cache/
      - ./s2s_pipeline.py:/usr/src/app/s2s_pipeline.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - neo4j-network

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    networks:
      - neo4j-network
    ports:
      - '7888:7474'
      - '7999:7687'
    environment:
      - NEO4J_AUTH=neo4j/testtest
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]